name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing this.
on: [push]
jobs:
  explore-github-actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "First GHA!"
      - run: echo "Event name -> ${{ github.event_name }}"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
  second-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Second job!?"